// #############################################################################
// #                                                                           #
// #   Copyright Bigster 2021 All Rights Reserved                              #
// #                                                                           #
// #############################################################################

@endpoint=http://127.0.0.1:4000

# @TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MTkwM2MzYS0xNDViLTExZWMtODJhOC0wMjQyYWMxMzAwMDMiLCJpYXQiOjE2MzE4NDQzMDN9.TJDiDxKd7aHd4_28-zRgTpXbL5U22U_-YZm_j8DOGYk


###########################################
# create finance quotes
###########################################

POST  {{endpoint}}/api/v1/quotes/finance HTTP/1.1
Content-Type: application/json 

{
    "quote": "It's not how much money you make, but how much you keep, how hard it works for you and how many generations you keep it for."
}

###########################################
# create love quotes
###########################################
POST  {{endpoint}}/api/v1/quotes/love HTTP/1.1
Content-Type: application/json 

{
    "quote": "The giving of love is an education in itself."
}

###########################################
# create LIFE quotes
###########################################
POST  {{endpoint}}/api/v1/quotes/life HTTP/1.1
Content-Type: application/json 

{
    "quote": "You have to choose between the Pain of Dscipline OR the Pain of Regret."
}

###########################################
# create LOVE quotes
###########################################
POST  {{endpoint}}/api/v1/quotes/love HTTP/1.1
Content-Type: application/json 

{
    "quote": "There is no love more sincere than the love of food."
}

###########################################
# create FINANCE quotes
###########################################
POST  {{endpoint}}/api/v1/quotes/finance HTTP/1.1
Content-Type: application/json 

{
    "quote": "Success if never making the same mistake twice."
}

# ###########################################
# # DELETE QUOTE quotes
# ###########################################
# DELETE   {{endpoint}}/api/v1/quotes/life/13 HTTP/1.1
# Content-Type: application/json 

###########################################
# Get All Quotes of a given Type
###########################################

GET {{endpoint}}/api/v1/quotes/LIFE HTTP/1.1
Content-Type: application/json 
# Authorization: Bearer {{TOKEN}}


###########################################
# Get ramdom quote of a given type
###########################################

GET {{endpoint}}/api/v1/quote/life HTTP/1.1
Content-Type: application/json 
# Authorization: Bearer {{TOKEN}}

###

###########################################
# Get quote of a given type by Id 
###########################################

GET {{endpoint}}/api/v1/quote/finance/6 HTTP/1.1
Content-Type: application/json 
# Authorization: Bearer {{TOKEN}}

###

GET {{endpoint}}/api/v1/quote/life/6 HTTP/1.1
Content-Type: application/json 
# Authorization: Bearer {{TOKEN}}


###########################################
# EDIT QUOTE(:type/:id)
###########################################
PUT {{endpoint}}/api/v1/quotes/life/6 HTTP/1.1
Content-Type: application/json 

{
    "quote": "Success is never making the same mistake twice."
}

###

###########################################
# DELETE QUOTE(/quotes/:type/:id)
###########################################
DELETE  {{endpoint}}/api/v1/quotes/life/13 HTTP/1.1
Content-Type: application/json 
