basePath: /api/v1
host: localhost:4000
info:
  contact:
    email: chigaji@gmail.com
    name: Ronald
    url: brothermen.com
  description: This is an API for My favorite quotes
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: My Favorite Quotes
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
